### ISSUE TITLE
Python crash

### ISSUE THREAD

**Issue by b-reich** [mickaelperrin/ansible-bitwarden-lookup-plugin#1]
I got the following error when I use the lookup module

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 592, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python3.7/site-packages/ansible/playbook/task.py", line 268, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python3.7/site-packages/ansible/playbook/base.py", line 435, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python3.7/site-packages/ansible/template/__init__.py", line 584, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python3.7/site-packages/ansible/template/__init__.py", line 539, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python3.7/site-packages/ansible/template/__init__.py", line 804, in do_template
    res = j2_concat(rf)
  File "<template>", line 11, in root
  File "/usr/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/ansible/template/__init__.py", line 687, in _lookup
    instance = self._lookup_loader.get(name.lower(), loader=self._loader, templar=self)
  File "/usr/lib/python3.7/site-packages/ansible/plugins/loader.py", line 559, in get
    self._load_config_defs(name, self._module_cache[path], path)
  File "/usr/lib/python3.7/site-packages/ansible/plugins/loader.py", line 292, in _load_config_defs
    dstring = AnsibleLoader(getattr(module, 'DOCUMENTATION', ''), file_name=path).get_single_data()
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 3, column 15

fatal: [192.168.188.117]: FAILED! => {
    "msg": "Unexpected failure during module execution."
}
```

**Comment by b-reich** [comment]
bw and bw-simple works fine

**Comment by mickaelperrin** [comment]
I guess there is something wrong with your YAML. Did you try to validate it using a YAML validator / linter ?

**Comment by b-reich** [comment]
The yamil is valid
